### ISSUE TITLE
base_report_designer installation Fail

### ISSUE THREAD

**Issue by elektryx** [odoo/odoo-extra#106]
Hello,

i Need help.
I use odoo 9.0c on Windows and get the following issue, if i try to install base_report_designer.
Thank you.

> Odoo Server Error
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 647, in _handle_exception
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 684, in dispatch
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 320, in _call_function
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\service\model.py", line 118, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 313, in checked_call
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 963, in __call__
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\http.py", line 513, in response_wrap
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\web\controllers\main.py", line 901, in call_button
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\web\controllers\main.py", line 889, in _call_kw
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 250, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 250, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\modules\registry.py", line 386, in new
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\modules\loading.py", line 338, in load_modules
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\modules\loading.py", line 237, in load_marked_modules
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\modules\loading.py", line 156, in load_module_graph
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\modules\loading.py", line 98, in _load_data
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\tools\convert.py", line 851, in convert_file
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\tools\convert.py", line 938, in convert_xml_import
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\tools\convert.py", line 801, in parse
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\tools\convert.py", line 804, in parse
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\tools\convert.py", line 708, in _tag_record
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 250, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\base\ir\ir_model.py", line 1143, in _update
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 250, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\openerp\addons\base\ir\ir_ui_view.py", line 353, in create
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 250, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 354, in old_api
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\models.py", line 4157, in create
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 248, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 490, in new_api
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\models.py", line 4354, in _create
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\api.py", line 248, in wrapper
>   File "C:\Program Files (x86)\Odoo 9.0-20160801\server\.\openerp\models.py", line 1271, in _validate_fields
> ParseError: "Invalid view definition
> 
> Fehlerdetails:
> View inheritance may not use attribute 'string' as a selector.
> 
> Fehler Kontext:
> Ansicht `Form View: Odoo Report Designer Installation`
> [view_id: 594, xml_id: k. A., model: base_report_designer.installer, parent_id: 3]
> None" while parsing file:///C:/Program%20Files%20(x86)/Odoo%209.0-20160801/server/openerp/addons/base_report_designer/base_report_designer_installer.xml:4, near
> <record id="view_report_designer_installer" model="ir.ui.view">
>             <field name="name">Form View: Odoo Report Designer Installation</field>
>             <field name="model">base_report_designer.installer</field>
>             <field name="inherit_id" ref="base.res_config_installer"/>
>             <field name="arch" type="xml">
>                 <data>
>                     <form position="attributes">
>                         <attribute name="string">Odoo Report Designer Configuration</attribute>
>                     </form>
>                     <separator string="title" position="before">
>                         <label string="This plug-in allows you to create/modify Odoo Reports into OpenOffice Writer."/>
>                     </separator>
>                     <xpath expr="//button[@string='Install Modules']" position="replace">
>                         <button name="action_next" type="object" string="Configure" invisible="context.get('menu',False)" class="oe_highlight"/>
>                         <label string="or" invisible="context.get('menu',False)" class="oe_inline"/>
>                     </xpath>
>                     <xpath expr="//button[@string='Skip']" position="replace">
>                         <button string="Ok" class="oe_highlight" special="cancel" invisible="context.get('active_model',False)"/>
>                         <button string="Skip" class="oe_link" special="cancel" invisible="context.get('menu',False)"/>
>                     </xpath>
>                     <xpath expr="//separator[@string='title']" position="after">
>                         <group colspan="8" height="450" width="750">
>                             <field name="name" invisible="1"/>
>                             <field name="plugin_file" filename="name" widget="url"/>
>                             <separator string="Installation and Configuration Steps" colspan="4"/>
>                             <field name="description" nolabel="1" colspan="8"/>
>                         </group>
>                     </xpath>
>                     <separator string="title" position="attributes">
>                         <attribute name="string">Odoo Report Designer</attribute>
>                     </separator>
>                 </data>
>             </field>
>         </record>

**Comment by axatech01** [comment]
Second @elektryx .

Same behavior:



  Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 705, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1161, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 360, in create
    context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4174, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4371, in _create
    recs._validate_fields(vals)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 1281, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Detalles de error:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `Form View:   Report Designer Installation`
[view_id: 2066, xml_id: n/a, model: base_report_designer.installer, parent_id: 3]
None" while parsing /var/lib/ /addons/9.0/base_report_designer/base_report_designer_installer.xml:4, near
<record id="view_report_designer_installer" model="ir.ui.view">
            <field name="name">Form View:   Report Designer Installation</field>
            <field name="model">base_report_designer.installer</field>
            <field name="inherit_id" ref="base.res_config_installer"/>
            <field name="arch" type="xml">
                <data>
                    <form position="attributes">
                        <attribute name="string">  Report Designer Configuration</attribute>
                    </form>
                    <separator string="title" position="before">
                        <label string="This plug-in allows you to create/modify   Reports into OpenOffice Writer."/>
                    </separator>
                    <xpath expr="//button[@string='Install Modules']" position="replace">
                        <button name="action_next" type="object" string="Configure" invisible="context.get('menu',False)" class="oe_highlight"/>
                        <label string="or" invisible="context.get('menu',False)" class="oe_inline"/>
                    </xpath>
                    <xpath expr="//button[@string='Skip']" position="replace">
                        <button string="Ok" class="oe_highlight" special="cancel" invisible="context.get('active_model',False)"/>
                        <button string="Skip" class="oe_link" special="cancel" invisible="context.get('menu',False)"/>
                    </xpath>
                    <xpath expr="//separator[@string='title']" position="after">
                        <group colspan="8" height="450" width="750">
                            <field name="name" invisible="1"/>
                            <field name="plugin_file" filename="name" widget="url"/>
                            <separator string="Installation and Configuration Steps" colspan="4"/>
                            <field name="description" nolabel="1" colspan="8"/>
                        </group>
                    </xpath>
                    <separator string="title" position="attributes">
                        <attribute name="string">  Report Designer</attribute>
                    </separator>
                </data>
            </field>
        </record>
