### ISSUE TITLE
I have this eror, what is the solution ??

### ISSUE THREAD

**Issue by fauzi55** [odoo/odoo-extra#109]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
2017-01-20 16:09:22,543 10456 ERROR runbot_3 openerp.addons.base.ir.ir_cron: Call of self.pool.get('runbot.repo').cron(cr, uid, *()) failed in Job 2
Traceback (most recent call last):
  File "/opt/odoo099/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/opt/odoo099/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo099/addons/runbot/runbot.py", line 444, in cron
    self.update(cr, uid, ids, context=context)
  File "/opt/odoo099/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo099/addons/runbot/runbot.py", line 276, in update
    self.update_git(cr, uid, repo)
  File "/opt/odoo099/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo099/addons/runbot/runbot.py", line 300, in update_git
    repo.git(['fetch', '-p', 'origin', '+refs/heads/*:refs/heads/*'])
  File "/opt/odoo099/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo099/openerp/api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo099/addons/runbot/runbot.py", line 238, in git
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', u'--git-dir=/opt/odoo099/addons/runbot/static/repo/git_gitlab.com_fauzi2_Tes_runbot.git', 'fetch', '-p', 'origin', '+refs/heads/*:refs/heads/*']' returned non-zero exit status 128

**Comment by cayadisutanto** [comment]
Anyone have solution on this issue? This problem occured when I run start script as service. Direct call has no error.
