### ISSUE TITLE
Facing the import error UserError

### ISSUE THREAD

**Issue by yongsern** [odoo/odoo-extra#130]
Commit ID: f5003ef9bedbe0ef065825c6f0304e43190906b7

2018-01-22 04:53:17,163 16192 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/yslau/odoo-8.0/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/home/yslau/odoo-8.0/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/yslau/odoo-8.0/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/yslau/odoo-8.0/openerp/http.py", line 1295, in __call__
    self.load_addons()
  File "/home/yslau/odoo-8.0/openerp/http.py", line 1316, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/yslau/odoo-8.0/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/yslau/odoo-8.0/odoo-extra/website_twitter_wall/__init__.py", line 22, in <module>
    import controllers
  File "/home/yslau/odoo-8.0/odoo-extra/website_twitter_wall/controllers/__init__.py", line 2, in <module>
    import main
  File "/home/yslau/odoo-8.0/odoo-extra/website_twitter_wall/controllers/main.py", line 7, in <module>
    from openerp.addons.website_twitter_wall.models.oauth import Oauth
  File "/home/yslau/odoo-8.0/odoo-extra/website_twitter_wall/models/__init__.py", line 3, in <module>
    import twitter_agent
  File "/home/yslau/odoo-8.0/odoo-extra/website_twitter_wall/models/twitter_agent.py", line 4, in <module>
    from openerp.exceptions import UserError
ImportError: cannot import name UserError

**Comment by elhamdaoui** [comment]
Hello,
try to use

     from openerp.osv import fields, osv
      ....
     osv.except_osv(_('Error!')
