### ISSUE TITLE
[master] runbot: Install runbot module with `test enable` return fails

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo-extra#60]
```python
odoo@3e39c391e3d1:~#
/odoo/odoo-8.0/openerp-server -d openerp_test3 --stop-after-init --log-level info --addons-path /odoo/workspace/src/github.com/odoo/odoo-extra,/odoo/runbot-addons,/odoo/odoo-8.0/addons --test-enable -i runbot
2015-04-20 22:27:17,405 2523 INFO ? openerp: OpenERP version 8.0
2015-04-20 22:27:17,405 2523 INFO ? openerp: addons paths: ['/odoo/.local/share/Odoo/addons/8.0', u'/odoo/workspace/src/github.com/Vauxoo/odoo-extra', u'/odoo/runbot-addons', u'/odoo/odoo-8.0/addons', '/odoo/odoo-8.0/openerp/addons']
2015-04-20 22:27:17,406 2523 INFO ? openerp: database hostname: localhost
2015-04-20 22:27:17,406 2523 INFO ? openerp: database port: 5432
2015-04-20 22:27:17,406 2523 INFO ? openerp: database user: odoo
2015-04-20 22:27:17,497 2523 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-04-20 22:27:17,502 2523 INFO openerp_test3 openerp.modules.loading: loading 1 modules...
2015-04-20 22:27:17,509 2523 INFO openerp_test3 openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2015-04-20 22:27:17,639 2523 WARNING openerp_test3 openerp.modules.loading: invalid module names, ignored: runbot_prebuild
2015-04-20 22:27:17,654 2523 INFO openerp_test3 openerp.modules.loading: loading 28 modules...
2015-04-20 22:27:17,696 2523 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-04-20 22:27:17,706 2523 INFO openerp_test3 openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2015-04-20 22:27:17,841 2523 INFO openerp_test3 openerp.addons.report.models.report: Upgrade Wkhtmltopdf to (at least) 0.12.0
2015-04-20 22:27:18,264 2523 INFO openerp_test3 openerp.modules.module: module runbot: creating or updating database tables
2015-04-20 22:27:18,317 2523 INFO openerp_test3 openerp.modules.loading: loading runbot/runbot.xml
2015-04-20 22:27:18,637 2523 INFO openerp_test3 openerp.modules.loading: loading runbot/res_config_view.xml
2015-04-20 22:27:18,662 2523 INFO openerp_test3 openerp.modules.loading: loading runbot/security/runbot_security.xml
2015-04-20 22:27:18,842 2523 INFO openerp_test3 openerp.modules.loading: loading runbot/security/ir.model.access.csv
2015-04-20 22:27:18,873 2523 INFO openerp_test3 openerp.modules.loading: loading runbot/security/ir.rule.csv
2015-04-20 22:27:19,546 2523 INFO openerp_test3 openerp.modules.module: module runbot_cla: creating or updating database tables
2015-04-20 22:27:19,575 2523 INFO openerp_test3 openerp.modules.loading: 28 modules loaded in 1.92s, 0 queries
2015-04-20 22:27:19,936 2523 INFO openerp_test3 openerp.modules.loading: Modules loaded.
2015-04-20 22:27:19,962 2523 INFO openerp_test3 openerp.modules.module: openerp.addons.website.tests.test_crawl running tests.
2015-04-20 22:27:19,963 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: test_10_crawl_public (openerp.addons.website.tests.test_crawl.Crawler)
2015-04-20 22:27:19,972 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: Anonymous Coward /
2015-04-20 22:27:20,500 2523 INFO ? openerp.http: HTTP Configuring static files
2015-04-20 22:27:20,502 2523 INFO openerp_test3 openerp.addons.base.ir.ir_http: Generating routing map
2015-04-20 22:27:20,550 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET / HTTP/1.1" 302 -
2015-04-20 22:27:20,633 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /runbot HTTP/1.1" 200 -
2015-04-20 22:27:20,634 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: Anonymous Coward /page/website.contactus
2015-04-20 22:27:20,638 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /page/website.contactus HTTP/1.1" 301 -
2015-04-20 22:27:20,674 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /page/contactus HTTP/1.1" 200 -
2015-04-20 22:27:20,675 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: Anonymous Coward /page/website.aboutus
2015-04-20 22:27:20,679 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /page/website.aboutus HTTP/1.1" 301 -
2015-04-20 22:27:20,702 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /page/aboutus HTTP/1.1" 200 -
2015-04-20 22:27:20,704 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: public crawled 3 urls in 0.73s 273 queries, 0.245s 91.00q per request,
2015-04-20 22:27:20,705 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: test_20_crawl_demo (openerp.addons.website.tests.test_crawl.Crawler)
2015-04-20 22:27:20,792 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:20] "GET /login?login=demo&db=openerp_test3&key=demo HTTP/1.1" 303 -
2015-04-20 22:27:21,124 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /web HTTP/1.1" 200 -
2015-04-20 22:27:21,125 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: demo /
2015-04-20 22:27:21,134 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET / HTTP/1.1" 302 -
2015-04-20 22:27:21,140 2523 WARNING openerp_test3 openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: runbot.repo
2015-04-20 22:27:21,143 2523 WARNING openerp_test3 openerp.addons.website.models.ir_http: 403 Forbidden:

Traceback (most recent call last):
  File "/odoo/odoo-8.0/addons/website/models/ir_http.py", line 196, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/odoo/odoo-8.0/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-8.0/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-8.0/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-8.0/openerp/http.py", line 677, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-8.0/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-8.0/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/odoo/odoo-8.0/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-8.0/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/odoo/workspace/src/github.com/Vauxoo/odoo-extra/runbot/runbot.py", line 1019, in repo
    repo_ids = repo_obj.search(cr, uid, [])
  File "/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-8.0/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-8.0/openerp/models.py", line 4615, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-8.0/openerp/models.py", line 3477, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/odoo/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/odoo/odoo-8.0/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-8.0/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Runbot/User\n\t- Runbot/Manager\n\n(Document model: runbot.repo)')

2015-04-20 22:27:21,203 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /runbot HTTP/1.1" 403 -
2015-04-20 22:27:21,204 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: FAIL
2015-04-20 22:27:21,204 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: test_30_crawl_admin (openerp.addons.website.tests.test_crawl.Crawler)
2015-04-20 22:27:21,294 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /login?login=admin&db=openerp_test3&key=admin HTTP/1.1" 303 -
2015-04-20 22:27:21,742 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /web HTTP/1.1" 200 -
2015-04-20 22:27:21,743 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /
2015-04-20 22:27:21,752 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET / HTTP/1.1" 302 -
2015-04-20 22:27:21,880 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /runbot HTTP/1.1" 200 -
2015-04-20 22:27:21,882 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /page/website.themes
2015-04-20 22:27:21,889 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /page/website.themes HTTP/1.1" 301 -
2015-04-20 22:27:21,955 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:21] "GET /page/themes HTTP/1.1" 200 -
2015-04-20 22:27:21,958 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /website/theme_change
2015-04-20 22:27:22,049 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /website/theme_change HTTP/1.1" 200 -
2015-04-20 22:27:22,052 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /website/theme_change?theme_id=website.theme_amelia
2015-04-20 22:27:22,180 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /website/theme_change?theme_id=website.theme_amelia HTTP/1.1" 200 -
2015-04-20 22:27:22,183 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /page/website.contactus
2015-04-20 22:27:22,187 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /page/website.contactus HTTP/1.1" 301 -
2015-04-20 22:27:22,246 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /page/contactus HTTP/1.1" 200 -
2015-04-20 22:27:22,248 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin /page/website.aboutus
2015-04-20 22:27:22,252 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /page/website.aboutus HTTP/1.1" 301 -
2015-04-20 22:27:22,297 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "GET /page/aboutus HTTP/1.1" 200 -
2015-04-20 22:27:22,301 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: admin crawled 6 urls in 1.10s 520 queries, 0.183s 86.67q per request
2015-04-20 22:27:22,302 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: ======================================================================
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: FAIL: test_20_crawl_demo (openerp.addons.website.tests.test_crawl.Crawler)
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: Traceback (most recent call last):
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: `   File "/odoo/odoo-8.0/addons/website/tests/test_crawl.py", line 81, in test_20_crawl_demo
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: `     seen = self.crawl('/', msg='demo')
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: `   File "/odoo/odoo-8.0/addons/website/tests/test_crawl.py", line 38, in crawl
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: `     self.assertIn( code, xrange(200, 300), "%s Fetching %s returned error response (%d)" % (msg, url, code))
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: ` AssertionError: 403 not found in xrange(200, 300) : demo Fetching / returned error response (403)
2015-04-20 22:27:22,302 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl: Ran 3 tests in 2.339s
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.addons.website.tests.test_crawl: FAILED
2015-04-20 22:27:22,302 2523 INFO openerp_test3 openerp.addons.website.tests.test_crawl:  (failures=1)
2015-04-20 22:27:22,302 2523 ERROR openerp_test3 openerp.modules.module: Module website: 1 failures, 0 errors
2015-04-20 22:27:22,306 2523 INFO openerp_test3 openerp.modules.module: openerp.addons.report.tests.test_reports running tests.
2015-04-20 22:27:22,307 2523 INFO openerp_test3 openerp.addons.report.tests.test_reports: test_reports (openerp.addons.report.tests.test_reports.TestReports)
2015-04-20 22:27:22,308 2523 INFO openerp_test3 openerp.addons.report.tests.test_reports: Ran 1 test in 0.001s
2015-04-20 22:27:22,308 2523 INFO openerp_test3 openerp.addons.report.tests.test_reports: OK
2015-04-20 22:27:22,321 2523 INFO openerp_test3 openerp.modules.module: openerp.addons.base.tests.test_xmlrpc running tests.
2015-04-20 22:27:22,321 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: test_01_xmlrpc_login (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-04-20 22:27:22,321 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: ` Try to login on the common service.
2015-04-20 22:27:22,400 2523 INFO openerp_test3 openerp.service.common: successful login from 'admin' using database 'openerp_test3'
2015-04-20 22:27:22,400 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "POST /xmlrpc/2/common HTTP/1.1" 200 -
2015-04-20 22:27:22,401 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: test_xmlrpc_ir_model_search (openerp.addons.base.tests.test_xmlrpc.test_xmlrpc)
2015-04-20 22:27:22,401 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: ` Try a search on the object service.
2015-04-20 22:27:22,403 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "POST /xmlrpc/2/object HTTP/1.1" 200 -
2015-04-20 22:27:22,407 2523 INFO openerp_test3 werkzeug: 127.0.0.1 - - [20/Apr/2015 22:27:22] "POST /xmlrpc/2/object HTTP/1.1" 200 -
2015-04-20 22:27:22,409 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: Ran 2 tests in 0.088s
2015-04-20 22:27:22,409 2523 INFO openerp_test3 openerp.addons.base.tests.test_xmlrpc: OK
2015-04-20 22:27:22,409 2523 INFO openerp_test3 openerp.modules.loading: All post-tested in 2.45s, 1226 queries
2015-04-20 22:27:22,409 2523 INFO openerp_test3 openerp.service.server: Initiating shutdown
2015-04-20 22:27:22,409 2523 INFO openerp_test3 openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
odoo@3e39c391e3d1:~#
```

**Comment by moylop260** [comment]
FYI this issue is fixed with next pr:
https://github.com/OCA/runbot-addons/pull/68/files

If the pr is good for you then I can create a new one for this odoo-extra
