### ISSUE TITLE
Thunderbird plugin can't be installed

### ISSUE THREAD

**Issue by macz1971** [odoo/odoo-extra#71]
Plugin version: 8.0.1.0

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4265, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `plugin_name` does not exist

Error context:
View `plugin_thunderbird.installer.view`
[view_id: 1094, xml_id: n/a, model: plugin_thunderbird.installer, parent_id: 3]" while parsing /opt/odoo/addons/plugin_thunderbird/plugin_thunderbird.xml:4, near
<record id="view_thunderbird_installer" model="ir.ui.view">
            <field name="name">plugin_thunderbird.installer.view</field>
            <field name="model">plugin_thunderbird.installer</field>
            <field name="inherit_id" ref="base.res_config_installer"/>
            <field name="arch" type="xml">
                <data>
                    <form position="attributes">
                        <attribute name="string">Install Thunderbird Plug-In</attribute>
                    </form>
                    <xpath expr="//footer" position="replace">
                       <footer>
                            <button string="Close" class="oe_link" special="cancel"/>
                       </footer>
                    </xpath>
                    <xpath expr="//separator[@string='title']" position="after">
                        <group>
                            <field name="thunderbird" invisible="1"/>
                            <field name="plugin_name" invisible="1"/>
                            <field name="plugin_file" filename="plugin_name" widget="url"/>
                        </group>
                        <separator string="Installation and Configuration Steps"/>
                        <p>Thunderbird plug-in installation:</p>
                        <ol>
                            <li> Save the Thunderbird plug-in.</li>
                            <li> From the Thunderbird menubar: Tools &#173;&gt; Add-ons -&gt; Screwdriver/Wrench Icon -&gt; Install add-on from file...</li>
                            <li> Select the plug-in (the file named openerp_plugin.xpi).</li>
                            <li> Click "Install Now".</li>
                            <li> Restart Thunderbird.</li>
                            <li> From the Thunderbird menubar: OpenERP -&gt; Configuration.</li>
                            <li> Configure your openerp server.</li>
                        </ol>
                    </xpath>
                    <separator string="title" position="attributes">
                        <attribute name="string"/>
                    </separator>
                </data>
            </field>
        </record>

**Comment by rim-odoo** [comment]
From https://github.com/odoo/odoo-extra/blob/master/README.md 
```
This repository holds an archive of Odoo modules that are not maintained anymore by the publisher. Use them at your own risk.
```
